application:
  name: shuttleapi
  project: shuttleapiproject
  publicly_accessible: true
databases:
  - type: postgresql
    version: "11.5"
    name: shuttleapi
routers:
  - name: main
    routes:
      - application_name: shuttleapi
        paths:
          - /*